### ISSUE TITLE
JWIN issue with Sleeping Bag Mod

### ISSUE THREAD

**Issue by VizionG** [ssblur/Just-What-I-Needed-Mod#10]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (LoadingProfiler-MC1.9-1.3.jar)
  LoadingPlugin (Quark-beta-18.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  CCCDeobfPlugin (unknown)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 07-05-2016 21:03
Description: Ticking player

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at net.minecraft.block.Block.getBedDirection(Block.java:1295)
	at com.reimaginedgaming.blur.jwin.events.PlayerHandlers.sleepfix(PlayerHandlers.java:129)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_PlayerHandlers_sleepfix_PlayerSleepInBedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.shadowfacts.sleepingbag.ItemSleepingBag.vanillaCanSleep(ItemSleepingBag.java:151)
	at net.shadowfacts.sleepingbag.ItemSleepingBag.canPlayerSleep(ItemSleepingBag.java:172)
	at net.shadowfacts.sleepingbag.ItemSleepingBag.onArmorTick(ItemSleepingBag.java:122)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:347)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:497)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1961)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:301)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:286)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at net.minecraft.block.Block.getBedDirection(Block.java:1295)
	at com.reimaginedgaming.blur.jwin.events.PlayerHandlers.sleepfix(PlayerHandlers.java:129)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_PlayerHandlers_sleepfix_PlayerSleepInBedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.shadowfacts.sleepingbag.ItemSleepingBag.vanillaCanSleep(ItemSleepingBag.java:151)
	at net.shadowfacts.sleepingbag.ItemSleepingBag.canPlayerSleep(ItemSleepingBag.java:172)
	at net.shadowfacts.sleepingbag.ItemSleepingBag.onArmorTick(ItemSleepingBag.java:122)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:347)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:497)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1961)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 268
	Entity Name: VizionG
	Entity's Exact location: -175,48, 58,00, 165,72
	Entity's Block location: World: (-176,58,165), Chunk: (at 0,3,5 in -11,10; contains blocks -176,0,160 to -161,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0,00, -0,08, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:301)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:286)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@6dc3aafd
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 716589576 bytes (683 MB) / 2010120192 bytes (1917 MB) up to 4149739520 bytes (3957 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4451m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.23 Powered by Forge 12.16.1.1891 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1891.jar) 
	UCHIJAAAA	Forge{12.16.1.1891} [Minecraft Forge] (forge-1.9-12.16.1.1891.jar) 
	UCHIJAAAA	CodeChickenCore{2.0.1.53} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	JEI{3.3.3.197} [Just Enough Items] (jei_1.9-3.3.3.197.jar) 
	UCHIJAAAA	abyssalcraft{1.9.1.5} [AbyssalCraft] (AbyssalCraft-1.9-1.9.1.5.jar) 
	UCHIJAAAA	acblocks{1.0.0} [AbyssalBlocks] (AbyssalBlocks-1.9-1.0.0.jar) 
	UCHIJAAAA	actuallyadditions{1.9-r31} [Actually Additions] (ActuallyAdditions-1.9-r31.jar) 
	UCHIJAAAA	bagginses{2.3.0b} [Bagginses] (Bagginses-1.9-2.3.0b.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.0} [Better Builder's Wands] (BetterBuildersWands-0.6.0-1.9r124+c748dee.jar) 
	UCHIJAAAA	BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
	UCHIJAAAA	blockdrops{1.0.0} [Block Drops] (Block Drops-1.9-1.0.0.jar) 
	UCHIJAAAA	bookshelf{1.2.0.226} [Bookshelf] (Bookshelf-1.9-1.2.0.237.jar) 
	UCHIJAAAA	bookshelfapi{3.0.4} [Bookshelf] (Bookshelf-API-1.9-3.0.4.jar) 
	UCHIJAAAA	BuildersGuides{1.9-0.2.0-beta} [Builder's Guides] (buildersguides-1.9-0.2.0-beta.jar) 
	UCHIJAAAA	chameleoncreepers{1.4} [Chameleon Creepers] (ChameleonCreepers-1.9-1.4.jar) 
	UCHIJAAAA	chancecubes{1.9-2.1.1.98} [Chance Cubes] (ChanceCubes-1.9-2.1.1.98.jar) 
	UCHIJAAAA	ChestTransporter{2.3.0} [Chest Transporter] (ChestTransporter-2.3.0-MC1.9.jar) 
	UCHIJAAAA	ChickenChunks{2.0.1.26} [ChickenChunks] (ChickenChunks-1.9-2.0.1.26-universal.jar) 
	UCHIJAAAA	claybucket{1.0} [Clay Bucket] (ClayBucket-1.9-1.0.jar) 
	UCHIJAAAA	craftingtweaks{4.0.10} [Crafting Tweaks] (craftingtweaks-mc1.9-4.0.10.jar) 
	UCHIJAAAA	MineTweaker3{3.0.7} [MineTweaker 3] (CraftTweaker-Customized-1.9-3.0.7.jar) 
	UCHIJAAAA	DarkUtils{1.1.0.32} [Dark Utilities] (DarkUtilities-1.9-1.1.0.33.jar) 
	UCHIJAAAA	double_jump{1.0.0} [DoubleJump] (Double Jump-1.9-1.0.0.jar) 
	UCHIJAAAA	DurabilityShow{3.0.2} [Durability Show] (Durability Show-1.9-3.0.2.jar) 
	UCHIJAAAA	shetiphiancore{3.2.1} [ShetiPhian-Core] (shetiphiancore-1.9.0-3.2.1.jar) 
	UCHIJAAAA	endertanks{1.3.2} [EnderTanks] (endertanks-1.9.0-1.3.2.jar) 
	UCHIJAAAA	FFS{1.9-1.5.1.1.2} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9-1.5.1.1.2.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJAAAA	graves{1.9-b10-universal} [Graves Mod] (graves-1.9-b10-universal.jar) 
	UCHIJAAAA	inventorysorter{0.7.14+32} [Simple Inventory sorting] (inventorysorter-1.9-0.7.14+32.jar) 
	UCHIJAAAA	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCHIJAAAA	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.5.27} [Just Enough Resources] (JustEnoughResources-1.9-0.4.5.27.jar) 
	UCHIJAAAA	jwin{univ_compat_filler} [Just What I Needed] (jwin-0.12.3.jar) 
	UCHIJAAAA	LoadingProfiler{1.1} [Loading Profiler] (LoadingProfiler-MC1.9-1.3.jar) 
	UCHIJAAAA	mantle{1.9-0.10.0.jenkins132} [Mantle] (Mantle-1.9-0.10.0.jar) 
	UCHIJAAAA	modularsystems{3.0.2} [Modular Systems] (ModularSystems-1.9-3.0.2.jar) 
	UCHIJAAAA	shear{1.1} [More Shearables] (MoreShearables1.1.1-1.9.jar) 
	UCHIJAAAA	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.9.jar) 
	UCHIJAAAA	NashornLib{1.9.0-1.8.77-1.2.1} [Nashorn Library] (NashornLib-1.9.0-1.8.77-1.2.1.5.jar) 
	UCHIJAAAA	harvestcraft{1.9a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9a.jar) 
	UCHIJAAAA	Quark{beta-18} [Quark] (Quark-beta-18.jar) 
	UCHIJAAAA	reborncore{2.1.0.53} [RebornCore] (RebornCore-1.9-2.1.0.53-universal.jar) 
	UCHIJAAAA	rftools{4.46} [RFTools] (rftools-1.9.0-4.46.jar) 
	UCHIJAAAA	rouletteores{1.2.21} [RouletteOres] (RouletteOres-1.2.21.jar) 
	UCHIJAAAA	routerreborn{1.9-4.0.1.11b_universal} [Router Reborn] (RouterReborn-1.9-4.0.1.11b_universal.jar) 
	UCHIJAAAA	shadowmc{3.1.0} [ShadowMC] (ShadowMC-1.9-3.1.4.jar) 
	UCHIJAAAA	SleepingBag{1.1.0} [Sleeping Bag] (SleepingBag-1.9-1.1.0.jar) 
	UCHIJAAAA	tconstruct{1.9-2.3.0.jenkins193} [Tinkers' Construct] (TConstruct-1.9-2.3.0.jar) 
	UCHIJAAAA	techreborn{1.0.6.197} [TechReborn] (TechReborn-1.9-1.0.6.197-universal.jar) 
	UCHIJAAAA	Woot{1.9-0.5.0-beta} [Woot] (woot-1.9-0.5.0-beta.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (LoadingProfiler-MC1.9-1.3.jar)
  lumien.loadingprofiler.asm.ClassTransformer
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
CCCDeobfPlugin (unknown)
  
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['VizionG'/268, l='World #2', x=-175,48, y=58,00, z=165,72]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ssblur** [comment]
Thank you for pointing this out, I will be sure to deal with it.

**Comment by ssblur** [comment]
Should be fixed now, sorry about that.

**Comment by UnstableCodeScarlet** [comment]
Not fixed, Now the issue is on servers.
Though instead of crashing the server or client, It disconnects the player with an "Internal Server error"
Log part that matters- http://puu.sh/r4Z7s/e206541e55.txt
Have fun!

Man it's gonna suck fixing this on my server until a patched is released....
\sigh\
